name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # allows you to trigger manually

defaults:
  run:
    shell: bash -l {0}

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest # x86-64
          - ubuntu-24.04-arm # ARM
          # FIXME linker error `Library not loaded: @rpath/libblosc.1.dylib`
          # - macos-15-intel # x86-64
          # - macos-latest # ARM
          # FIXME compiler error `Cannot open include file: 'hdf5.h'`
          # - windows-latest  # x86-64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.56.0
          environments: default

      - name: Build
        run: pixi run build

      - name: Unit tests
        run: pixi run test
